<!DOCTYPE html>
<html>
<head>
  <title>Java 中的异常和处理详解</title>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="JAVA,异常处理机制" />
  <meta name="description" content="Java 中的异常和处理详解" />
  <link href="/templets/default/css/bootstrap.min.css" rel="stylesheet">
  <link href="/templets/default/css/bootstrap-theme.min.css" rel="stylesheet">
  <link href="/templets/default/css/theme.css" rel="stylesheet">
  <link href="/templets/default/css/main.css" rel="stylesheet">
  <link href="/templets/default/css/animate.css" rel="stylesheet">
  <link href="/templets/default/css/header.css" rel="stylesheet">
</head>
<body>
  <header id="header" class="site-header">
    <div class="container" style="margin-top:0px;">
      <div class="row">
        <div class="col-sm-12 col-md-12">
          <div class="site-header-banner" style="min-height:170px;">
            <h2 class="title-site-name swing animated" id="title-site-name">一起学编程</h2>
            <div class="title-site-domain" id="title-site-domain">www.yqxbc.com</div>
            <div class="title-site-memo" id="title-site-memo">常用技术，开发中遇到的坑，你想要的或许这里有。</div>
          </div>
        </div>
      </div>
    </div>
    <nav class="navbar navbar-default navbar-custom">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header navbar-header-custom">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">首页</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav nav-custom">
            <li class="dropdown">
              <a href="/bcsj" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">编程设计<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/bcsj/css/" title="CSS">CSS</a> </li>
                <li><a href="/bcsj/hadoop/" title="Hadoop">Hadoop</a> </li>
                <li><a href="/bcsj/ajax/" title="Ajax">Ajax</a> </li>
                <li><a href="/bcsj/js/" title="Javascript">Javascript</a> </li>
                <li><a href="/bcsj/java/" title="Java">Java</a> </li>
                <li><a href="/bcsj/jetty/" title="Jetty">Jetty</a> </li>
                <li><a href="/bcsj/python/" title="Python">Python</a> </li>
                <li><a href="/storm/" title="Storm">Storm</a> </li>
                <li><a href="/elasticsearch/" title="ElasticSearch">ElasticSearch</a> </li>
                <li><a href="/SpringBoot/" title="SpringBoot">SpringBoot</a> </li>
                <li><a href="/sublime/" title="Sublime">Sublime</a> </li>
                <li><a href="/springcloud/" title="SpringCloud">SpringCloud</a> </li>
                <li><a href="/zookeeper/" title="ZooKeeper">ZooKeeper</a> </li>
                <li><a href="/git/" title="Git">Git</a> </li>
                <li><a href="/maven/" title="Maven">Maven</a> </li>
                <li><a href="/gradle/" title="Gradle">Gradle</a> </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="/shujuku" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">数据库 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/shujuku/redis/" title="redis">redis</a> </li>
                <li><a href="/shujuku/sqlserver/" title="SQL Server">SQL Server</a> </li>
                <li><a href="/shujuku/memcache/" title="Memcache">Memcache</a> </li>
                <li><a href="/shujuku/mysql/" title="MySql">MySql</a> </li>
                <li><a href="/shujuku/oracle/" title="Oracle">Oracle</a> </li>
                <li><a href="/shujuku/mangodb/" title="MangoDB">MangoDB</a> </li>
                <li><a href="/shujuku/hbase/" title="Hbase">Hbase</a> </li>
                <li><a href="/shujuku/access/" title="Access">Access</a> </li>
                <li><a href="/shujuku/db2/" title="DB2">DB2</a> </li>
              </ul>
            </li>
            <li><a href="/dnzs" target="_blank" title="电脑基础知识学习，计算机技术学习网站，计算机基础知识,电脑学习">电脑知识 <span class="sr-only">(current)</span></a></li>
            <li><a href="/wlzs" target="_blank" title="网络知识大全">网络知识</a></li>
            <li><a href="http://www.win10os.com"target="_blank" title="windows10系统">windows10</a></li>
            <li><a href="/czxt/linux" target="_blank" title="linux系统">linux</a></li>
            <li><a href="/erweima/" target="_blank" title="二维码生成">常用工具</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header><!-- /header -->

  <div class="modal fade" id="imgModal" tabindex="-1" role="dialog" aria-hidden="true">
	   <div class="modal-dialog">
		  <div class="modal-content">
			 <div class="modal-body">
				<div id="modal_img" ></div>
			 </div>
		  </div>
	   </div>
	</div>
  <div class="container" style="padding-left:0px;padding-right:0px">
    
    <div class="col-sm-8  col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="art_title">
            <div>Java 中的异常和处理详解</div>
            <a href="/">yqxbc</a>  发布时间：05-22 来源：0 浏览：0次
          </div>
          <div class="art_body">
            <div class="col-md-12 well bg-success" role="complementary">
              <h3>文章目录</h3>
            	<nav>
            		<ul id="rootul" class="nav bs-docs-sidenav"></ul>		
            	</nav>
            </div>
            <div id="85251406" class="art_content"><h2>简介</h2>

<p>程序运行时，发生的不被期望的事件，它阻止了程序按照程序员的预期正常执行，这就是异常。异常发生时，是任程序自生自灭，立刻退出终止，还是输出错误给用户？或者用C语言风格：用函数返回值作为执行状态？。</p>

<p>Java提供了更加优秀的解决办法：异常处理机制。</p>

<p>异常处理机制能让程序在异常发生时，按照代码的预先设定的异常处理逻辑，针对性地处理异常，让程序尽最大可能恢复正常并继续执行，且保持代码的清晰。<br />
Java中的异常可以是函数中的语句执行时引发的，也可以是程序员通过throw 语句手动抛出的，只要在Java程序中产生了异常，就会用一个对应类型的异常对象来封装异常，JRE就会试图寻找异常处理程序来处理异常。</p>

<p>Throwable类是Java异常类型的顶层父类，一个对象只有是 Throwable 类的（直接或者间接）实例，他才是一个异常对象，才能被异常处理机制识别。JDK中内建了一些常用的异常类，我们也可以自定义异常。</p>

<h2>Java异常的分类和类结构图</h2>

<p>Java标准裤内建了一些通用的异常，这些类以Throwable为顶层父类。</p>

<p>Throwable又派生出Error类和Exception类。</p>

<p>错误：Error类以及他的子类的实例，代表了JVM本身的错误。错误不能被程序员通过代码处理，Error很少出现。因此，程序员应该关注Exception为父类的分支下的各种异常类。</p>

<p>异常：Exception以及他的子类，代表程序运行时发送的各种不期望发生的事件。可以被Java异常处理机制使用，是异常处理的核心。</p>

<p><a href="http://www.importnew.com/26613.html/858860-20170911125844719-1230755033"><img alt="" src="http://incdn1.b0.upaiyun.com/2017/09/994bd262fec543853cd99fe680e857cc.png" /></a></p>

<p>总体上我们根据Javac对异常的处理要求，将异常类分为2类。</p>

<p>非检查异常（unckecked exception）：Error 和 RuntimeException 以及他们的子类。javac在编译时，不会提示和发现这样的异常，不要求在程序处理这些异常。所以如果愿意，我们可以编写代码处理（使用try&hellip;catch&hellip;finally）这样的异常，也可以不处理。对于这些异常，我们应该修正代码，而不是去通过异常处理器处理 。这样的异常发生的原因多半是代码写的有问题。如除0错误ArithmeticException，错误的强制类型转换错误ClassCastException，数组索引越界ArrayIndexOutOfBoundsException，使用了空对象NullPointerException等等。</p>

<p>检查异常（checked exception）：除了Error 和 RuntimeException的其它异常。javac强制要求程序员为这样的异常做预备处理工作（使用try&hellip;catch&hellip;finally或者throws）。在方法中要么用try-catch语句捕获它并处理，要么用throws子句声明抛出它，否则编译不会通过。这样的异常一般是由程序的运行环境导致的。因为程序可能被运行在各种未知的环境下，而程序员无法干预用户如何使用他编写的程序，于是程序员就应该为这样的异常时刻准备着。如SQLException , IOException,ClassNotFoundException 等。</p>

<p>需要明确的是：检查和非检查是对于javac来说的，这样就很好理解和区分了。</p>

<h2>初识异常</h2>

<p>下面的代码会演示2个异常类型：ArithmeticException 和 InputMismatchException。前者由于整数除0引发，后者是输入的数据不能被转换为int类型引发。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>package</code>&nbsp;<code>com.example;</code></p>

			<p><code>import</code>&nbsp;<code>java. util .Scanner ;</code></p>

			<p><code>public</code>&nbsp;<code>class</code>&nbsp;<code>AllDemo</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main (String [] args )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System . out. println(&nbsp;</code><code>&quot;----欢迎使用命令行除法计算器----&quot;</code>&nbsp;<code>) ;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>CMDCalculate ();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>CMDCalculate ()</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>Scanner scan =&nbsp;</code><code>new</code>&nbsp;<code>Scanner ( System. in );</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>num1 = scan .nextInt () ;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>num2 = scan .nextInt () ;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>result = devide (num1 , num2 ) ;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System . out. println(&nbsp;</code><code>&quot;result:&quot;</code>&nbsp;<code>+ result) ;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>scan .close () ;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>devide (</code><code>int</code>&nbsp;<code>num1,&nbsp;</code><code>int</code>&nbsp;<code>num2 ){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>num1 / num2 ;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>

			<p><code>/*****************************************</code></p>

			<p>&nbsp;</p>

			<p><code>----欢迎使用命令行除法计算器----</code></p>

			<p><code>0</code></p>

			<p><code>Exception in thread &quot;main&quot; java.lang.ArithmeticException : / by zero</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at com.example.AllDemo.devide( AllDemo.java:30 )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at com.example.AllDemo.CMDCalculate( AllDemo.java:22 )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at com.example.AllDemo.main( AllDemo.java:12 )</code></p>

			<p>&nbsp;</p>

			<p><code>----欢迎使用命令行除法计算器----</code></p>

			<p><code>r</code></p>

			<p><code>Exception in thread &quot;main&quot; java.util.InputMismatchException</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.throwFor( Scanner.java:864 )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.next( Scanner.java:1485 )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.nextInt( Scanner.java:2117 )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.nextInt( Scanner.java:2076 )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at com.example.AllDemo.CMDCalculate( AllDemo.java:20 )</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at com.example.AllDemo.main( AllDemo.java:12 )</code></p>

			<p><code>*****************************************/</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>异常是在执行某个函数时引发的，而函数又是层级调用，形成调用栈的，因为，只要一个函数发生了异常，那么他的所有的caller都会被异常影响。当这些被影响的函数以异常信息输出时，就形成的了异常追踪栈。</p>

<p>异常最先发生的地方，叫做异常抛出点。</p>

<p><a href="http://www.importnew.com/26613.html/858860-20170911121451422-233079767"><img alt="" src="http://incdn1.b0.upaiyun.com/2017/09/0b3e4ca2f4cf8d7116c7ad354940601f.png" /></a></p>

<p>从上面的例子可以看出，当devide函数发生除0异常时，devide函数将抛出ArithmeticException异常，因此调用他的CMDCalculate函数也无法正常完成，因此也发送异常，而CMDCalculate的caller&mdash;&mdash;main 因为CMDCalculate抛出异常，也发生了异常，这样一直向调用栈的栈底回溯。这种行为叫做异常的冒泡，异常的冒泡是为了在当前发生异常的函数或者这个函数的caller中找到最近的异常处理程序。由于这个例子中没有使用任何异常处理机制，因此异常最终由main函数抛给JRE，导致程序终止。</p>

<p>上面的代码不使用异常处理机制，也可以顺利编译，因为2个异常都是非检查异常。但是下面的例子就必须使用异常处理机制，因为异常是检查异常。</p>

<p>代码中我选择使用throws声明异常，让函数的调用者去处理可能发生的异常。但是为什么只throws了IOException呢？因为FileNotFoundException是IOException的子类，在处理范围内。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>@Test</code></p>

			<p><code>public</code>&nbsp;<code>void</code>&nbsp;<code>testException()&nbsp;</code><code>throws</code>&nbsp;<code>IOException</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//FileInputStream的构造函数会抛出FileNotFoundException</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>FileInputStream fileIn =&nbsp;</code><code>new</code>&nbsp;<code>FileInputStream(</code><code>&quot;E:\\a.txt&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>word;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//read方法会抛出IOException</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>while</code><code>((word =&nbsp; fileIn.read())!=-</code><code>1</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.print((</code><code>char</code><code>)word);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//close方法会抛出IOException</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>fileIn.clos</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<h2>异常处理的基本语法</h2>

<p>在编写代码处理异常时，对于检查异常，有2种不同的处理方式：使用try&hellip;catch&hellip;finally语句块处理它。或者，在函数签名中使用throws 声明交给函数调用者caller去解决。</p>

<p>try&hellip;catch&hellip;finally语句块</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>try</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//try块中放可能发生异常的代码。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//如果执行完try且不发生异常，则接着去执行finally块和finally后面的代码（如果有的话）。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//如果发生异常，则尝试去匹配catch块。</code></p>

			<p>&nbsp;</p>

			<p><code>}</code><code>catch</code><code>(SQLException SQLexception){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//每一个catch块用于捕获并处理一个特定的异常，或者这异常类型的子类。Java7中可以将多个异常声明在一个catch中。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//catch后面的括号定义了异常类型和异常参数。如果异常与之匹配且是最先匹配到的，则虚拟机将使用这个catch块来处理异常。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//在catch块中可以使用这个块的异常参数来获取异常的相关信息。异常参数是这个catch块中的局部变量，其它块不能访问。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//如果当前try块中发生的异常在后续的所有catch中都没捕获到，则先去执行finally，然后到这个函数的外部caller中去匹配异常处理器。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//如果try中没有发生异常，则所有的catch块将被忽略。</code></p>

			<p>&nbsp;</p>

			<p><code>}</code><code>catch</code><code>(Exception exception){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//...</code></p>

			<p><code>}</code><code>finally</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//finally块通常是可选的。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;</code><code>//无论异常是否发生，异常是否匹配被处理，finally都会执行。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;</code><code>//一个try至少要有一个catch块，否则， 至少要有1个finally块。但是finally不是用来处理异常的，finally不会捕获异常。</code></p>

			<p><code>&nbsp;&nbsp;</code><code>//finally主要做一些清理工作，如流的关闭，数据库连接的关闭等。</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p><strong>需要注意的地方</strong></p>

<p>1、try块中的局部变量和catch块中的局部变量（包括异常变量），以及finally中的局部变量，他们之间不可共享使用。</p>

<p>2、每一个catch块用于处理一个异常。异常匹配是按照catch块的顺序从上往下寻找的，只有第一个匹配的catch会得到执行。匹配时，不仅运行精确匹配，也支持父类匹配，因此，如果同一个try块下的多个catch异常类型有父子关系，应该将子类异常放在前面，父类异常放在后面，这样保证每个catch块都有存在的意义。</p>

<p>3、java中，异常处理的任务就是将执行控制流从异常发生的地方转移到能够处理这种异常的地方去。也就是说：当一个函数的某条语句发生异常时，这条语句的后面的语句不会再执行，它失去了焦点。执行流跳转到最近的匹配的异常处理catch代码块去执行，异常被处理完后，执行流会接着在&ldquo;处理了这个异常的catch代码块&rdquo;后面接着执行。<br />
有的编程语言当异常被处理后，控制流会恢复到异常抛出点接着执行，这种策略叫做：resumption model of exception handling（恢复式异常处理模式 ）<br />
而Java则是让执行流恢复到处理了异常的catch块后接着执行，这种策略叫做：termination model of exception handling（终结式异常处理模式）</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main(String[] args){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>foo();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>catch</code><code>(ArithmeticException ae) {</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(</code><code>&quot;处理异常&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>

			<p><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>foo(){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>a =&nbsp;</code><code>5</code><code>/</code><code>0</code><code>;&nbsp;&nbsp;</code><code>//异常抛出点</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(</code><code>&quot;为什么还不给我涨工资!!!&quot;</code><code>);&nbsp;&nbsp;</code><code>//////////////////////不会执行</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>throws 函数声明</p>

<p>throws声明：如果一个方法内部的代码会抛出检查异常（checked exception），而方法自己又没有完全处理掉，则javac保证你必须在方法的签名上使用throws关键字声明这些可能抛出的异常，否则编译不通过。</p>

<p>throws是另一种处理异常的方式，它不同于try&hellip;catch&hellip;finally，throws仅仅是将函数中可能出现的异常向调用者声明，而自己则不具体处理。</p>

<p>采取这种异常处理的原因可能是：方法本身不知道如何处理这样的异常，或者说让调用者处理更好，调用者需要为可能发生的异常负责。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>void</code>&nbsp;<code>foo()&nbsp;</code><code>throws</code>&nbsp;<code>ExceptionType1 , ExceptionType2 ,ExceptionTypeN</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//foo内部可以抛出 ExceptionType1 , ExceptionType2 ,ExceptionTypeN 类的异常，或者他们的子类的异常对象。</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<h2>finally块</h2>

<p>finally块不管异常是否发生，只要对应的try执行了，则它一定也执行。只有一种方法让finally块不执行：System.exit()。因此finally块通常用来做资源释放操作：关闭文件，关闭数据库连接等等。</p>

<p>良好的编程习惯是：在try块中打开资源，在finally块中清理释放这些资源。</p>

<p>需要注意的地方:</p>

<p>1、finally块没有处理异常的能力。处理异常的只能是catch块。</p>

<p>2、在同一try&hellip;catch&hellip;finally块中 ，如果try中抛出异常，且有匹配的catch块，则先执行catch块，再执行finally块。如果没有catch块匹配，则先执行finally，然后去外面的调用者中寻找合适的catch块。</p>

<p>3、在同一try&hellip;catch&hellip;finally块中 ，try发生异常，且匹配的catch块中处理异常时也抛出异常，那么后面的finally也会执行：首先执行finally块，然后去外围调用者中寻找合适的catch块。</p>

<p>这是正常的情况，但是也有特例。关于finally有很多恶心，偏、怪、难的问题，我在本文最后统一介绍了，电梯速达-&gt;：finally块和return</p>

<h2>throw 异常抛出语句</h2>

<p>throw exceptionObject</p>

<p>程序员也可以通过throw语句手动显式的抛出一个异常。throw语句的后面必须是一个异常对象。</p>

<p>throw 语句必须写在函数中，执行throw 语句的地方就是一个异常抛出点，它和由JRE自动形成的异常抛出点没有任何差别。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>void</code>&nbsp;<code>save(User user)</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>if</code><code>(user&nbsp; ==&nbsp;</code><code>null</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>IllegalArgumentException(</code><code>&quot;User对象为空&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//......</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<h2>异常的链化</h2>

<p>在一些大型的，模块化的软件开发中，一旦一个地方发生异常，则如骨牌效应一样，将导致一连串的异常。假设B模块完成自己的逻辑需要调用A模块的方法，如果A模块发生异常，则B也将不能完成而发生异常，但是B在抛出异常时，会将A的异常信息掩盖掉，这将使得异常的根源信息丢失。异常的链化可以将多个模块的异常串联起来，使得异常信息不会丢失。</p>

<p>异常链化:以一个异常对象为参数构造新的异常对象。新的异对象将包含先前异常的信息。这项技术主要是异常类的一个带Throwable参数的函数来实现的。这个当做参数的异常，我们叫他根源异常（cause）。</p>

<p>查看Throwable类源码，可以发现里面有一个Throwable字段cause，就是它保存了构造时传递的根源异常参数。这种设计和链表的结点类设计如出一辙，因此形成链也是自然的了。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>class</code>&nbsp;<code>Throwable&nbsp;</code><code>implements</code>&nbsp;<code>Serializable {</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>private</code>&nbsp;<code>Throwable cause =&nbsp;</code><code>this</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>Throwable(String message, Throwable cause) {</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>fillInStackTrace();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>detailMessage = message;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>this</code><code>.cause = cause;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>Throwable(Throwable cause) {</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>fillInStackTrace();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>detailMessage = (cause==</code><code>null</code>&nbsp;<code>?&nbsp;</code><code>null</code>&nbsp;<code>: cause.toString());</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>this</code><code>.cause = cause;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//........</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>下面是一个例子，演示了异常的链化：从命令行输入2个int，将他们相加，输出。输入的数不是int，则导致getInputNumbers异常，从而导致add函数异常，则可以在add函数中抛出</p>

<p>一个链化的异常。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main(String[] args)</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(</code><code>&quot;请输入2个加数&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>result;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result = add();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(</code><code>&quot;结果:&quot;</code><code>+result);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>catch</code>&nbsp;<code>(Exception e){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>e.printStackTrace();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>

			<p><code>//获取输入的2个整数返回</code></p>

			<p><code>private</code>&nbsp;<code>static</code>&nbsp;<code>List&lt;Integer&gt; getInputNumbers()</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>List&lt;Integer&gt; nums =&nbsp;</code><code>new</code>&nbsp;<code>ArrayList&lt;&gt;();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>Scanner scan =&nbsp;</code><code>new</code>&nbsp;<code>Scanner(System.in);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>num1 = scan.nextInt();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>num2 = scan.nextInt();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>nums.add(</code><code>new</code>&nbsp;<code>Integer(num1));</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>nums.add(</code><code>new</code>&nbsp;<code>Integer(num2));</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>catch</code><code>(InputMismatchException immExp){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>immExp;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>finally</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>scan.close();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>nums;</code></p>

			<p><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>//执行加法计算</code></p>

			<p><code>private</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>add()&nbsp;</code><code>throws</code>&nbsp;<code>Exception</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>result;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>List&lt;Integer&gt; nums =getInputNumbers();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result = nums.get(</code><code>0</code><code>)&nbsp; + nums.get(</code><code>1</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>catch</code><code>(InputMismatchException immExp){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>Exception(</code><code>&quot;计算失败&quot;</code><code>,immExp);&nbsp;&nbsp;</code><code>/////////////////////////////链化:以一个异常对象为参数构造新的异常对象。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;&nbsp;<code>result;</code></p>

			<p><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>/*</code></p>

			<p><code>请输入2个加数</code></p>

			<p><code>r 1</code></p>

			<p><code>java.lang.Exception: 计算失败</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at practise.ExceptionTest.add(ExceptionTest.java:53)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at practise.ExceptionTest.main(ExceptionTest.java:18)</code></p>

			<p><code>Caused by: java.util.InputMismatchException</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.throwFor(Scanner.java:864)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.next(Scanner.java:1485)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.nextInt(Scanner.java:2117)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at java.util.Scanner.nextInt(Scanner.java:2076)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at practise.ExceptionTest.getInputNumbers(ExceptionTest.java:30)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>at practise.ExceptionTest.add(ExceptionTest.java:48)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>... 1 more</code></p>

			<p>&nbsp;</p>

			<p><code>*/</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p><a href="http://www.importnew.com/26613.html/858860-20170913181056469-1080507673"><img alt="" src="http://incdn1.b0.upaiyun.com/2017/09/88140decdb2955dcb0dfac0e7a4440a7.png" /></a></p>

<h2>自定义异常</h2>

<p>如果要自定义异常类，则扩展Exception类即可，因此这样的自定义异常都属于检查异常（checked exception）。如果要自定义非检查异常，则扩展自RuntimeException。</p>

<p>按照国际惯例，自定义的异常应该总是包含如下的构造函数：</p>

<p>一个无参构造函数</p>

<p>一个带有String参数的构造函数，并传递给父类的构造函数。</p>

<p>一个带有String参数和Throwable参数，并都传递给父类构造函数</p>

<p>一个带有Throwable 参数的构造函数，并传递给父类的构造函数。</p>

<p>下面是IOException类的完整源代码，可以借鉴。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>class</code>&nbsp;<code>IOException&nbsp;</code><code>extends</code>&nbsp;<code>Exception</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>static</code>&nbsp;<code>final</code>&nbsp;<code>long</code>&nbsp;<code>serialVersionUID = 7818375828146090155L;</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>IOException()</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>super</code><code>();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>IOException(String message)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>super</code><code>(message);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>IOException(String message, Throwable cause)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>super</code><code>(message, cause);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>IOException(Throwable cause)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>super</code><code>(cause);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<h2>异常的注意事项</h2>

<p>1、当子类重写父类的带有 throws声明的函数时，其throws声明的异常必须在父类异常的可控范围内&mdash;&mdash;用于处理父类的throws方法的异常处理器，必须也适用于子类的这个带throws方法 。这是为了支持多态。</p>

<p>例如，父类方法throws 的是2个异常，子类就不能throws 3个及以上的异常。父类throws IOException，子类就必须throws IOException或者IOException的子类。</p>

<p>至于为什么？我想，也许下面的例子可以说明。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>class</code>&nbsp;<code>Father</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>void</code>&nbsp;<code>start()&nbsp;</code><code>throws</code>&nbsp;<code>IOException</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>IOException();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>class</code>&nbsp;<code>Son&nbsp;</code><code>extends</code>&nbsp;<code>Father</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>void</code>&nbsp;<code>start()&nbsp;</code><code>throws</code>&nbsp;<code>Exception</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>SQLException();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>

			<p><code>/**********************假设上面的代码是允许的（实质是错误的）***********************/</code></p>

			<p><code>class</code>&nbsp;<code>Test</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main(String[] args)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>Father[] objs =&nbsp;</code><code>new</code>&nbsp;<code>Father[</code><code>2</code><code>];</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>objs[</code><code>0</code><code>] =&nbsp;</code><code>new</code>&nbsp;<code>Father();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>objs[</code><code>1</code><code>] =&nbsp;</code><code>new</code>&nbsp;<code>Son();</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>for</code><code>(Father obj:objs)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//因为Son类抛出的实质是SQLException，而IOException无法处理它。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//那么这里的try。。catch就不能处理Son中的异常。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//多态就不能实现了。</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>obj.start();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>catch</code><code>(IOException)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//处理IOException</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>2、Java程序可以是多线程的。每一个线程都是一个独立的执行流，独立的函数调用栈。如果程序只有一个线程，那么没有被任何代码处理的异常 会导致程序终止。如果是多线程的，那么没有被任何代码处理的异常仅仅会导致异常所在的线程结束。</p>

<p>也就是说，Java中的异常是线程独立的，线程的问题应该由线程自己来解决，而不要委托到外部，也不会直接影响到其它线程的执行。</p>

<h2>finally块和return</h2>

<p>首先一个不容易理解的事实：在 try块中即便有return，break，continue等改变执行流的语句，finally也会执行。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main(String[] args)</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>re = bar();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(re);</code></p>

			<p><code>}</code></p>

			<p><code>private</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>bar()</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>5</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>finally</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(</code><code>&quot;finally&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>

			<p><code>/*输出：</code></p>

			<p><code>finally</code></p>

			<p><code>*/</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>很多人面对这个问题时，总是在归纳执行的顺序和规律，不过我觉得还是很难理解。我自己总结了一个方法。用如下GIF图说明。</p>

<p><a href="http://www.importnew.com/26613.html/858860-20170913191914985-125646869"><img alt="" src="http://incdn1.b0.upaiyun.com/2017/09/0471c2805ebd5a463211ced478eaf7f8.gif" /></a></p>

<p>也就是说：try&hellip;catch&hellip;finally中的return 只要能执行，就都执行了，他们共同向同一个内存地址（假设地址是0&times;80）写入返回值，后执行的将覆盖先执行的数据，而真正被调用者取的返回值就是最后一次写入的。那么，按照这个思想，下面的这个例子也就不难理解了。</p>

<p>finally中的return 会覆盖 try 或者catch中的返回值。</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main(String[] args)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>result;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result&nbsp; =&nbsp; foo();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(result);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>/////////2</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result = bar();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(result);&nbsp;&nbsp;&nbsp;&nbsp;</code><code>/////////2</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>@SuppressWarnings</code><code>(</code><code>&quot;finally&quot;</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>foo()</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>trz{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>a =&nbsp;</code><code>5</code>&nbsp;<code>/&nbsp;</code><code>0</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>catch</code>&nbsp;<code>(Exception e){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>1</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>finally</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>2</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>@SuppressWarnings</code><code>(</code><code>&quot;finally&quot;</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>bar()</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>1</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>finally</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>2</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>finally中的return会抑制（消灭）前面try或者catch块中的异常</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>class</code>&nbsp;<code>TestException</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main(String[] args)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>result;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result = foo();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(result);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//输出100</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>catch</code>&nbsp;<code>(Exception e){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(e.getMessage());&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//没有捕获到异常</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result&nbsp; = bar();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(result);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//输出100</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>catch</code>&nbsp;<code>(Exception e){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(e.getMessage());&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//没有捕获到异常</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//catch中的异常被抑制</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>@SuppressWarnings</code><code>(</code><code>&quot;finally&quot;</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>foo()&nbsp;</code><code>throws</code>&nbsp;<code>Exception</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>a =&nbsp;</code><code>5</code><code>/</code><code>0</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>1</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>catch</code><code>(ArithmeticException amExp) {</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>Exception(</code><code>&quot;我将被忽略，因为下面的finally中使用了return&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>finally</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>100</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//try中的异常被抑制</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>@SuppressWarnings</code><code>(</code><code>&quot;finally&quot;</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>bar()&nbsp;</code><code>throws</code>&nbsp;<code>Exception</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>a =&nbsp;</code><code>5</code><code>/</code><code>0</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>1</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>finally</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>100</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>finally中的异常会覆盖（消灭）前面try或者catch中的异常</p>

<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td>
			<p><code>class</code>&nbsp;<code>TestException</code></p>

			<p><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>void</code>&nbsp;<code>main(String[] args)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>result;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result = foo();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>catch</code>&nbsp;<code>(Exception e){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(e.getMessage());&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//输出：我是finaly中的Exception</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>result&nbsp; = bar();</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}&nbsp;</code><code>catch</code>&nbsp;<code>(Exception e){</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>System.out.println(e.getMessage());&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//输出：我是finaly中的Exception</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//catch中的异常被抑制</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>@SuppressWarnings</code><code>(</code><code>&quot;finally&quot;</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>foo()&nbsp;</code><code>throws</code>&nbsp;<code>Exception</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>a =&nbsp;</code><code>5</code><code>/</code><code>0</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>1</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>catch</code><code>(ArithmeticException amExp) {</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>Exception(</code><code>&quot;我将被忽略，因为下面的finally中抛出了新的异常&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>finally</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>Exception(</code><code>&quot;我是finaly中的Exception&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>//try中的异常被抑制</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>@SuppressWarnings</code><code>(</code><code>&quot;finally&quot;</code><code>)</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>public</code>&nbsp;<code>static</code>&nbsp;<code>int</code>&nbsp;<code>bar()&nbsp;</code><code>throws</code>&nbsp;<code>Exception</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>try</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>int</code>&nbsp;<code>a =&nbsp;</code><code>5</code><code>/</code><code>0</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>return</code>&nbsp;<code>1</code><code>;</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code><code>finally</code>&nbsp;<code>{</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>throw</code>&nbsp;<code>new</code>&nbsp;<code>Exception(</code><code>&quot;我是finaly中的Exception&quot;</code><code>);</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&nbsp;</p>

			<p><code>&nbsp;&nbsp;&nbsp;&nbsp;</code><code>}</code></p>

			<p><code>}</code></p>
			</td>
		</tr>
	</tbody>
</table>

<p>上面的3个例子都异于常人的编码思维，因此我建议：</p>

<p>不要在fianlly中使用return。</p>

<p>不要在finally中抛出异常。</p>

<p>减轻finally的任务，不要在finally中做一些其它的事情，finally块仅仅用来释放资源是最合适的。</p>

<p>将尽量将所有的return写在函数的最后面，而不是try &hellip; catch &hellip; finally中。</p>

<p>&nbsp;</p>
</div>
  		  <!-- 将此标记放在您希望显示like按钮的位置 -->          
            <div class="art_like"><div class="bdlikebutton"></div></div>
          </div>
        </div>
      </div>
      <div class="pnum">
        <div class="pages mypagelist">
          <div></div>
        </div>
      </div>
      <div class="pre_next">
        <nav>
          <ul class="pager">
            <li class="previous"></li>
            <li class="next"></li>
          </ul>
        </nav>
      </div>
      <div class="well"> 
    		如果你有好的<a href="http://www.win10os.com/win10zixun" title="win10资讯">win10资讯</a>或者<a href="http://www.win10os.com/win10jiqiao" title="win10教程">win10教程</a>，以及<a href="http://www.win10os.com/win10xitong" title="win10">win10</a>相关的问题想要获得<a href="http://www.win10os.com/win10xiazai" title="win10系统下载">win10系统下载</a>的关注与报道。<br/>欢迎加入发送邮件到657025171#qq.com(#替换为@)。期待你的好消息！
    	</div>
    </div>
    <!--右侧部分-->
    <div class="col-sm-4 col-md-4">
      <script src='/plus/ad_js.php?aid=12' language='javascript'></script>
      <div class="panel panel-custom panel-custom-right">
        <div class="panel-heading">最新文章>>></div>
        <div class="panel-body">
          <ul class="all_list">
            <li><a href='/bcsj/java/42949670.html'>《RocketMq》七、Broker中心节点</a></li><li><a href='/bcsj/java/59451787.html'>《RocketMq》六、Client－Consumer消费者详解</a></li><li><a href='/bcsj/java/93478184.html'>《RocketMq》五、Client－Producer生产者详解</a></li><li><a href='/bcsj/java/16882015.html'>《RocketMq》四、Client Producer/Consumer总览</a></li><li><a href='/bcsj/java/66636302.html'>《RocketMq》三、NameServer</a></li><li><a href='/bcsj/java/91963739.html'>《RocketMq》二、存储篇</a></li><li><a href='/bcsj/java/36422446.html'>《RocketMq》一、网络传输篇</a></li><li><a href='/bcsj/java/69287988.html'>linux jar包启动脚本</a></li><li><a href='/bcsj/java/89472738.html'>nginx 反向代理oss</a></li><li><a href='/bcsj/java/43423861.html'>细粒度 自定义注解 权限控制具体实现</a></li>
          </ul>
        </div>
      </div>  
      <script src='/plus/ad_js.php?aid=14' language='javascript'></script>
      <div id="scr_cont" class="panel panel-custom panel-custom-right">
        <div class="panel-heading">相关文章>>></div>
        <div class="panel-body">
          <ul class="all_list">
            <li><a href='/bcsj/java/1459.html'>maven国内快速镜像中央仓库地址,Aliyun镜像,OSChina镜像</a></li><li><a href='/bcsj/java/1439.html'>SpringMVC+JSP企业支付宝账号开发接口教程</a></li><li><a href='/bcsj/java/452.html'>在MyEclipse中搭建Spring MVC开发环境</a></li><li><a href='/bcsj/java/1365.html'>Java虚拟机(JVM)以及跨平台原理</a></li><li><a href='/bcsj/java/128.html'>错误整理：No plugin found for prefix 'jetty' in the current proje</a></li><li><a href='/bcsj/java/152.html'>HTTP大文件上传断点续传控件发布-Xproer.HttpUploader5</a></li><li><a href='/bcsj/java/1548.html'>Spring使用支付宝扫码支付</a></li><li><a href='/bcsj/java/1440.html'>JAVA环境变量JAVA_HOME、CLASSPATH、PATH设置详解</a></li><li><a href='/bcsj/java/728.html'>Java开发工具</a></li><li><a href='/bcsj/java/1362.html'>web service对外发布一个hello world接口</a></li>
          </ul>
          </ul>
        </div>
      </div>
      <div class="ad"></div>
    </div>
    
  </div>
  <nav class="navbar navbar-default navbar-fixed-bottom navbar-bottom-custom">
    <div class="container">
      <span class="pull-right navbar-text" id="font_smaller" onclick="changeFont('smaller')">A-</span>&nbsp;&nbsp;<span class="pull-right navbar-text" id="font_bigger" onclick="changeFont('bigger')">A+</span>
    </div>
  </nav>
  <div class="footer">
    <div class="foot">
      <br>
      一起学编程(原一起学编程网)是一家纯计算机技术学习、电脑学习、IT技术学习交流型网站，一起学编程(原一起学编程网)所载文章来源于网络，如果不慎侵犯了您的权益，请联系我们删除！站长QQ：657025171<br>
      <a href="/aboutus.html">关于我们</a> | <a href="/dashiji.html">大事记</a> | <a href="/jiazhiguan.html">网站价值观</a> | <a href="/contactus.html">联系我们</a> | <a href="/sitemap.xml">网站地图</a> | <a href="/copyright.html">版权声明</a><br>
      Copyright ◎ 2011 - 2018 yqxbc.com All Rights Reserved.<br>
      yqxbc.com 版权所有 京ICP备11048740号<br>

    </div>
  </div>
  <script src="/templets/default/js/jquery-2.1.3.js"></script>
  <script src="/templets/default/js/bootstrap.min.js"></script>
  <script src="/templets/default/js/docs.min.js"></script>
  <script src="/templets/default/js/main.js"></script>
  <script src="/templets/default/js/header.js"></script>
  <script src="/templets/default/js/article.js"></script>
  <script src="/templets/default/js/page-dir.js"></script>
  <script type="text/javascript">
    document.getElementById('count').innerHTML = document.getElementById('count_data').innerHTML;
      var img = $(".art_content p").find("img")
      $.each(img,function(index,el){
        el.style.width='100%';
      });
  </script>
  <!-- 将此代码放在适当的位置，建议在body结束前 -->
  <script id="bdlike_shell"></script>
  <script>
    var bdShare_config = {"type":"large","color":"blue","likeText":"内容很精彩","likedText":"您已顶过，谢谢！"};
    document.getElementById("bdlike_shell").src="http://bdimg.share.baidu.com/static/js/like_shell.js?t=" + Math.ceil(new Date()/3600000);
  </script>
</body>
</html>
